[tool.poetry]
name = "supabase-py"
version = "0.0.1"
description = "Supabase client for Python."
authors = ["Joel Lee <joel@joellee.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
postgrest-py = "^0.3.2"
realtime-py="^0.1.0"
gotrue="0.1.2"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
