[tool.poetry]
name = "supabase"
version = "0.0.3"
description = "Supabase client for Python."
authors = ["Joel Lee <joel@joellee.org>", "Leon Fedden <leonfedden@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
postgrest-py = {git = "https://github.com/supabase-community/postgrest-py.git", rev = "ba83ba43c6cfba906fbb710d3913e5dc070fdde3"}
realtime-py = "^0.1.2"
gotrue = {git = "https://github.com/supabase-community/gotrue-py.git", rev = "9ba3192dbdccd2f02a4819b52dd6cf51095af7e7"}
httpx = "^0.19.0"

[tool.poetry.dev-dependencies]
pre_commit = "^2.1.0"
black = "^21.7b0"
pytest = "^6.2.5"

[build-system]
requires = ["poetry>=0.12", "setuptools>=30.3.0,<50"]
build-backend = "poetry.masonry.api"
