[tool.poetry]
name = "supabase"
version = "0.1.1"
description = "Supabase client for Python."
authors = ["Joel Lee <joel@joellee.org>", "Leon Fedden <leonfedden@gmail.com>", "Daniel Reinón García <danielreinon@outlook.com>", "Leynier Gutiérrez González <leynier41@gmail.com>", "Anand"]
homepage = "https://github.com/supabase-community/supabase-py"
repository = "https://github.com/supabase-community/supabase-py"
documentation = "https://github.com/supabase-community/supabase-py"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.7"
postgrest-py = "^0.6.0"
realtime = "^0.0.4"
gotrue = "^0.3.0"
httpx = ">=0.19,<0.22"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
black = "^21.11b1"
pytest = "^6.2.5"
flake8 = "^4.0.1"
isort = "^5.9.3"
pytest-cov = "^3.0.0"
commitizen = "^2.20.3"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.1"
version_files = [
    "supabase/__init__.py",
    "pyproject.toml:version"
]
tag_format = "v$version"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
