[tool.poetry]
name = "supabase-py"
version = "0.0.2"
description = "Supabase client for Python."
authors = ["Joel Lee <joel@joellee.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7.1"
postgrest-py = "0.4.0"
realtime-py="^0.1.2"
realtime-py="^0.1.0"
gotrue="0.2.0"
pytest="6.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = [
    "poetry>=0.12",
    "setuptools>=30.3.0,<50",
]
build-backend = "poetry.masonry.api"
