[tool.poetry]
name = "supabase-py"
version = "0.0.1"
description = "Supabase client for Python."
authors = ["Lương Quang Mạnh <luongquangmanh85@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
postgrest-py = "^0.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
