[tool.poetry]
name = "supabase"
version = "0.0.3"
description = "Supabase client for Python."
authors = ["Joel Lee <joel@joellee.org>", "Leon Fedden <leonfedden@gmail.com>"]
homepage = "https://github.com/supabase-community/supabase-py"
repository = "https://github.com/supabase-community/supabase-py"
documentation = "https://github.com/supabase-community/supabase-py"
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.poetry.dependencies]
python = "^3.7"
postgrest-py = {git = "https://github.com/supabase-community/postgrest-py.git", rev = "3934fb2bd7c755962fa2fe490419d3e967e3555a"}
realtime-py = "^0.1.2"
gotrue = {git = "https://github.com/supabase-community/gotrue-py.git", rev = "9ba3192dbdccd2f02a4819b52dd6cf51095af7e7"}
httpx = ">=0.19,<0.22"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
black = "^21.11b1"
pytest = "^6.2.5"
flake8 = "^4.0.1"
isort = "^5.9.3"
pytest-cov = "^3.0.0"
commitizen = "^2.20.3"

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.3"
version_files = [
    "supabase/__init__.py",
    "pyproject.toml:version"
]
tag_format = "v$version"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
